### ISSUE TITLE
iOS builds broken with react-native-hms-location

### ISSUE THREAD

**Issue by ukasiu** [HMS-Core/hms-react-native-plugin#39]
**Description**
Importing `import HMSLocation from '@hmscore/react-native-hms-location';` causes iOS to build in runtime with
```
[Mon Nov 30 2020 12:29:30.290]  ERROR    TypeError: null is not an object (evaluating '_Geofence.default.GeofenceRequestConstants')
[Mon Nov 30 2020 12:29:30.291]  ERROR    Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)
```

**Environment**
 - Platform: React-Native
 - Kit: Location
 - Kit Version: 5.0.0-301-01

**Comment by ukasiu** [comment]
Similar affects also analytics kit: 
```
[Mon Nov 30 2020 12:39:18.599]  ERROR    TypeError: null is not an object (evaluating 'HmsAnalytics.HAEventType = _HAEventType.default') 
```

Please review all kits so that iOS builds won't fail.

**Comment by aktug** [comment]
Hello @ukasiu ;
Location plugin is not supporting iOS. That implementation is in our roadmap and we're working hard for that 👍👍

Please use 5.0.3-300 version of Analytics Kit, it is the initial version of supporting iOS. https://www.npmjs.com/package/@hmscore/react-native-hms-analytics/v/5.0.3-300

**Comment by ukasiu** [comment]
@aktug , I don't mean not supporting, but not breaking. In case of absence of HMS native module, just importing JS part should not cause runtime errors.

**Comment by aktug** [comment]
Hello again @ukasiu 
This issue has been fixed and waiting to release.
The next version 5.0.4.300 will be published at end of the December 👍

**Comment by ukasiu** [comment]
Hi @aktug ,

thanks for the good news!

**Comment by minUswachoke** [comment]
Please reopen this issue, 5.0.4.300 still does not fix this issue.

**Comment by sktan810** [comment]
the issue still exists even using 5.0.4.300

**Comment by uysalemre** [comment]
Hello @minUswachoke and @sktan810 ,

**First Solution**

1- First import Platform from react-native

`import { Platform } from "react-native";`

2- Define HMSLocation after your imports using let

`let HMSLocation;`

3- Check platform 

`
if (Platform.OS === "android") {
  HMSLocation = require("@hmscore/react-native-hms-location").default;
}
`

4- Now you can run your code.

**Second Solution**

You can use platform specific solutions as given [here](https://reactnative.dev/docs/platform-specific-code) by React Native.
